# -*- coding: utf-8 -*-
"""cornellaihealth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174YlW_nbbfnfMGQA8DrBRHVGyB-qLSxd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import sklearn
import pandas as pd
import glob
import os
import warnings
import torch

PHENOTYPES_DIR = Path("adult/phenotype")
FEATURES_DIR = Path("adult/features")

def clean_age_col(df: pd.DataFrame, default_age_val=np.nan) -> pd.DataFrame:
    """Replace the '90 and above' age sentinel with a numeric value (default NaN)."""
    df = df.copy()
    df["age"] = pd.to_numeric(
        df["age"].replace("90 and above", default_age_val),
        errors="coerce"
    )
    return df

demographics = pd.read_csv(
    PHENOTYPES_DIR / "demographics" / "demographics.tsv",
    sep="\t",
    dtype={"participant_id": str},
)
demographics = clean_age_col(demographics)

print(f"Rows: {len(demographics)}")
print(f"Columns: {demographics.shape[1]}")
print(demographics.columns.to_list())

demo_summary = (
    demographics[["participant_id", "sex_at_birth", "age"]]
    .drop_duplicates()
    .copy()
)
demo_summary["sex_at_birth"] = demo_summary["sex_at_birth"].fillna("Unknown")

age_stats = (
    demo_summary
    .groupby("sex_at_birth")["age"]
    .agg(
        N="count",
        Median=lambda x: round(x.median(), 1),
        Mean=lambda x: round(x.mean(), 1),
        SD=lambda x: round(x.std(), 1),
    )
    .reset_index()
)
age_stats

eligibility_table = pd.read_csv(
    PHENOTYPES_DIR / "enrollment" / "eligibility.tsv",
    sep="\t",
    dtype={"participant_id": str},
)
eligibility_table

resp_disorder_participants = eligibility_table[
    eligibility_table["eligible_studies___4"].notna()
].copy()
print(f"Respiratory disorder participants: {len(resp_disorder_participants)}")

(
    resp_disorder_participants
    .groupby("is_control_participant", dropna=False)
    .size()
    .reset_index(name="n")
)

airway_stenosis_dx = pd.read_csv(
    PHENOTYPES_DIR / "diagnosis" / "airway_stenosis.tsv",
    sep="\t",
    dtype={"participant_id": str},
)
print(airway_stenosis_dx.shape)
airway_stenosis_dx.dtypes

# Step 1: Cases
airway_stenosis_cases = (
    resp_disorder_participants
    .merge(airway_stenosis_dx, on="participant_id")
    .query("diagnosis_as_gold_standard_diagnosis == 'Yes'")
)

# Step 2: Controls
airway_stenosis_controls = (
    resp_disorder_participants
    .query("is_control_participant == 'Yes'")
)

# Step 3: Tidy
airway_stenosis_cases = (
    airway_stenosis_cases[["participant_id"]]
    .assign(status="case")
)
airway_stenosis_controls = (
    airway_stenosis_controls[["participant_id"]]
    .assign(status="control")
)

# Step 4: Combine
airway_stenosis_cohort = pd.concat(
    [airway_stenosis_cases, airway_stenosis_controls],
    ignore_index=True,
)

# Sanity check
airway_stenosis_cohort.groupby("status").size().reset_index(name="n")

stenosis_for_eda = (
    airway_stenosis_cohort
    .merge(demographics, on="participant_id")
    [["participant_id", "status", "age", "sex_at_birth"]]
    .drop_duplicates()
)

# Summary table
stenosis_for_eda.groupby("status")["age"].agg(
    N="count",
    Median=lambda x: round(x.median(), 1),
    Mean=lambda x: round(x.mean(), 1),
    SD=lambda x: round(x.std(), 1),
).reset_index()

fig, ax = plt.subplots(figsize=(6, 4))
sns.boxplot(
    data=stenosis_for_eda,
    x="status", y="age", hue="sex_at_birth",
    ax=ax, width=0.5,
)
sns.stripplot(
    data=stenosis_for_eda,
    x="status", y="age", hue="sex_at_birth",
    dodge=True, alpha=0.25, ax=ax,
    legend=False,
)
ax.set_title("Age by status and sex at birth")
ax.set_xlabel("Status")
ax.set_ylabel("Age")
sns.despine()
plt.tight_layout()
plt.show()

static_features_raw = pd.read_csv(
    FEATURES_DIR / "static_features.tsv",
    sep="\t",
    dtype={"participant_id": str},
)

# Which tasks are represented in our cohort?
(
    airway_stenosis_cohort
    .merge(static_features_raw, on="participant_id")
    [["participant_id", "status", "task_name"]]
    .groupby(["status", "task_name"])
    .size()
    .reset_index(name="n")
    .pivot(index="task_name", columns="status", values="n")
    .fillna(0)
    .astype(int)
)

print(static_features_raw["task_name"].unique().tolist())

stenosis_cohort_features = (
    airway_stenosis_cohort
    .merge(demographics, on="participant_id")
    .merge(static_features_raw, on="participant_id")
    .query("task_name == 'prolonged-vowel'")
)

print(stenosis_cohort_features.columns.tolist())

(
    stenosis_cohort_features
    .groupby("status")[["local_jitter", "local_shimmer"]]
    .agg(["count", "median", "mean", "std"])
    .round(4)
)

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

for ax, feature, title in zip(
    axes,
    ["local_jitter", "local_shimmer"],
    ["Jitter", "Shimmer"],
):
    plot_df = (
        stenosis_cohort_features
        [["participant_id", "status", "sex_at_birth", feature]]
        .dropna(subset=["sex_at_birth"])
    )
    sns.boxplot(data=plot_df, x="status", y=feature, hue="sex_at_birth", ax=ax, width=0.5)
    sns.stripplot(
        data=plot_df, x="status", y=feature, hue="sex_at_birth",
        dodge=True, alpha=0.25, ax=ax, legend=False,
    )
    ax.set_title(title)
    ax.set_xlabel("Status")
    ax.set_ylabel(feature)

sns.despine()
plt.tight_layout()
plt.show()

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report, confusion_matrix,
    roc_curve, roc_auc_score,
    precision_recall_curve, average_precision_score,
    ConfusionMatrixDisplay, RocCurveDisplay,
)

# --- Build design matrix ---
design_matrix = (
    stenosis_cohort_features
    [["status", "age", "sex_at_birth", "local_jitter", "local_shimmer"]]
    .dropna(subset=["sex_at_birth"])   # exclude cases with missing sex
    .dropna(subset=["age", "local_jitter", "local_shimmer"])  # drop rows with missing features
    .copy()
)

X = design_matrix.drop(columns="status")
y = design_matrix["status"]

numeric_features = ["age", "local_jitter", "local_shimmer"]
categorical_features = ["sex_at_birth"]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ]), numeric_features),
        ("cat", OneHotEncoder(drop="first", sparse_output=False), categorical_features),
    ]
)

design_matrix

np.random.seed(42)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    stratify=y,   # mirrors rsample's strata= argument
    random_state=42,
)

baseline = y_train.value_counts(normalize=True).reset_index()
baseline.columns = ["status", "prop"]
print(baseline)

glm_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000, random_state=42)),
])

glm_pipeline.fit(X_train, y_train)

y_pred_glm       = glm_pipeline.predict(X_test)
y_proba_glm      = glm_pipeline.predict_proba(X_test)

# sklearn orders classes alphabetically: [case, control]
class_labels     = glm_pipeline.classes_
case_idx         = list(class_labels).index("case")
y_score_glm_case = y_proba_glm[:, case_idx]

print(classification_report(y_test, y_pred_glm, target_names=class_labels))

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

# Confusion matrix
ConfusionMatrixDisplay.from_predictions(
    y_test, y_pred_glm, display_labels=class_labels, ax=axes[0]
)
axes[0].set_title("Logistic Regression — Confusion Matrix")

# ROC curve
RocCurveDisplay.from_predictions(
    (y_test == "case").astype(int),
    y_score_glm_case,
    name=f"LR (AUC = {roc_auc_score((y_test == 'case').astype(int), y_score_glm_case):.2f})",
    ax=axes[1],
)
axes[1].set_title("Logistic Regression — ROC Curve")
axes[1].plot([0, 1], [0, 1], "k--", lw=1)

plt.tight_layout()
plt.show()

rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(n_estimators=75, random_state=42)),
])

rf_pipeline.fit(X_train, y_train)

y_pred_rf       = rf_pipeline.predict(X_test)
y_proba_rf      = rf_pipeline.predict_proba(X_test)
y_score_rf_case = y_proba_rf[:, case_idx]

print(classification_report(y_test, y_pred_rf, target_names=class_labels))

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

# Confusion matrix
ConfusionMatrixDisplay.from_predictions(
    y_test, y_pred_rf, display_labels=class_labels, ax=axes[0]
)
axes[0].set_title("Random Forest — Confusion Matrix")

# ROC curve
RocCurveDisplay.from_predictions(
    (y_test == "case").astype(int),
    y_score_rf_case,
    name=f"RF (AUC = {roc_auc_score((y_test == 'case').astype(int), y_score_rf_case):.2f})",
    ax=axes[1],
)
axes[1].set_title("Random Forest — ROC Curve")
axes[1].plot([0, 1], [0, 1], "k--", lw=1)

plt.tight_layout()
plt.show()

def load_data(base_dir='adult'):
    phenotype_files = glob.glob(os.path.join(base_dir, 'phenotype', '**', '*.tsv'), recursive=True)
    feature_files = glob.glob(os.path.join(base_dir, 'features', '*.*'))

    dfs = {}

    print("Loading phenotype data...")
    for f in phenotype_files:
        name = os.path.basename(f).replace('.tsv', '')
        try:
            df = pd.read_csv(f, sep='\t', low_memory=False)

            # Standardize session_id column names if possible to improve join rate
            for col in df.columns:
                if col.endswith('session_id') and col != 'session_id':
                    df = df.rename(columns={col: 'session_id'})

            dfs[name] = df
            print(f" Loaded {name} ({df.shape[0]} rows, {df.shape[1]} cols)")
        except Exception as e:
            print(f" Failed to load {f}: {e}")

    print("\nLoading feature data...")
    for f in feature_files:
        if f.endswith('.tsv'):
            name = os.path.basename(f).replace('.tsv', '')
            try:
                df = pd.read_csv(f, sep='\t', low_memory=False)
                dfs[name] = df
                print(f" Loaded {name} ({df.shape[0]} rows, {df.shape[1]} cols)")
            except Exception as e:
                print(f" Failed to load {f}: {e}")
        elif f.endswith('.parquet'):
            name = os.path.basename(f).replace('.parquet', '')
            # Skip massive files to prevent OOM during join unless specifically requested.
            size_mb = os.path.getsize(f) / (1024 * 1024)
            if size_mb > 500:
                print(f" Skipping {name} due to large size ({size_mb:.1f} MB)")
                continue

            try:
                df = pd.read_parquet(f)
                dfs[name] = df
                print(f" Loaded {name} ({df.shape[0]} rows, {df.shape[1]} cols)")
            except Exception as e:
                print(f" Failed to load {f}: {e}")

    return dfs

def merge_all_data(dfs):
    print("\nMerging all dataframes...")
    if not dfs:
        return pd.DataFrame()

    # Sort dataframes by size (descending) so we use the largest (recording level) as the base table
    df_list = sorted(list(dfs.values()), key=lambda x: len(x), reverse=True)

    final_df = df_list[0]

    for i, df in enumerate(df_list[1:], 1):
        common_cols = list(set(final_df.columns).intersection(set(df.columns)))
        # Prefer merging on participant_id, session_id, and task_name
        merge_keys = [c for c in ['participant_id', 'session_id', 'task_name'] if c in common_cols]

        if not merge_keys:
            if 'participant_id' in final_df.columns and 'participant_id' in df.columns:
                merge_keys = ['participant_id']
            else:
                print(f" Warning: No common merge keys found for a dataframe, skipping.")
                continue

        # Drop intersecting columns that are not join keys to avoid duplicate column suffixes (_x, _y)
        cols_to_drop = [c for c in common_cols if c not in merge_keys]
        df = df.drop(columns=cols_to_drop)

        # CRITICAL FIX: Drop duplicates on the merge keys in the right table to avoid cartesian explosions!
        # Many tables have 1 row per participant, but if they have a rare duplicate, it exponentially multiplies rows.
        df = df.drop_duplicates(subset=merge_keys)

        for key in merge_keys:
            final_df[key] = final_df[key].astype(str)
            df[key] = df[key].astype(str)

        try:
            final_df = pd.merge(final_df, df, on=merge_keys, how='left')
        except Exception as e:
            print(f" Failed to merge a dataframe: {e}")

    return final_df

def main():
    dfs = load_data('adult')
    if not dfs:
        print("No data loaded.")
        return

    final_df = merge_all_data(dfs)
    print(f"\nFinal merged dataframe shape: {final_df.shape}")
    print("\nColumns (first 50):")
    print(final_df.columns.tolist()[:50])

    # Save the fully merged DF to a fast storage format or CSV if needed
    # final_df.to_csv('merged_adult_data.csv', index=False)
    # print("Saved merged data to merged_adult_data.csv")

    # Now the researcher can perform EDA on final_df here.
    return final_df

main()

!pip install 'senselab[audio]'

from senselab.audio.data_structures import Audio
from senselab.audio.tasks.preprocessing import resample_audios
from senselab.audio.tasks.features_extraction import extract_features_from_audios

def process_b2ai_audio(filepath: str):
    """
    Preprocesses user audio to match Bridge2AI standards and extracts features.
    """
    print(f"Loading audio from {filepath}...")
    # 1. Load the raw user audio
    raw_audio = Audio(filepath=filepath)

    # 2. Resample to 16 kHz (Bridge2AI standard)
    # Senselab handles monaural (mono) conversion natively
    print("Standardizing to 16000 Hz...")
    [standardized_audio] = resample_audios([raw_audio], resample_rate=16000)

    # 3. Extract Features
    print("Extracting acoustic features...")
    # This automatically extracts standard features (MFCCs, Pitch, Jitter, Shimmer, etc.)
    features = extract_features_from_audios([standardized_audio])

    print("Pipeline complete!")
    return standardized_audio, features[0]

# Example usage:
# clean_audio, extracted_data = process_b2ai_audio("test.wav.wav")

clean_audio, extracted_data = process_b2ai_audio("test.wav.wav")

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from IPython.display import display

def visualize_bridge2ai_features(features_dict, title_prefix=""):
    """
    Specifically tailored to visualize Bridge2AI-Voice extracted features in Colab.
    """
    for key, value in features_dict.items():
        name = key.lower()
        current_title = f"{title_prefix} > {key}" if title_prefix else key

        # 1. Handle Nested Dictionaries recursively
        if isinstance(value, dict):
            visualize_bridge2ai_features(value, current_title)
            continue

        # 2. Handle Text (Transcriptions)
        if isinstance(value, str):
            print(f"\n📝 [{current_title}] Transcription:")
            print(f"\"{value}\"")
            continue

        # 3. Handle Tabular Data (OpenSMILE)
        if isinstance(value, pd.DataFrame):
            print(f"\n📊 [{current_title}] OpenSMILE / Tabular Data (Shape: {value.shape}):")
            display(value.head())
            continue

        # Standardize arrays/tensors for plotting
        if isinstance(value, torch.Tensor):
            val_np = value.squeeze().detach().cpu().numpy()
        elif isinstance(value, np.ndarray):
            val_np = np.squeeze(value)
        else:
            # If it is a standard scalar (e.g., a single jitter/shimmer value)
            print(f"\n🔢 [{current_title}]: {value}")
            continue

        # 4. Handle 2D Heatmaps (Spectrograms, MFCCs, PPGs)
        if val_np.ndim == 2:
            plt.figure(figsize=(12, 4))

            # Select colormap based on feature type
            if "mfcc" in name:
                cmap = 'coolwarm'
                y_label = "MFCC Coefficients"
            elif "ppg" in name:
                cmap = 'viridis'
                y_label = "Phoneme Classes"
            else: # Spectrograms / Mel Spectrograms
                cmap = 'magma'
                y_label = "Frequency / Mel Bins"

            plt.imshow(val_np, aspect='auto', origin='lower', cmap=cmap)
            plt.title(f"2D Representation: {current_title}")
            plt.ylabel(y_label)
            plt.xlabel("Time Frames")
            plt.colorbar(format='%+2.2f')
            plt.tight_layout()
            plt.show()

        # 5. Handle 1D Time-Series (Pitch, Loudness, Articulatory Kinematics)
        elif val_np.ndim == 1:
            plt.figure(figsize=(12, 3))

            # Customize line color based on feature type
            color = 'coral' if 'pitch' in name or 'f0' in name else 'dodgerblue'

            plt.plot(val_np, color=color, linewidth=1.5)
            plt.title(f"1D Time-Series: {current_title}")
            plt.xlabel("Time Frames")
            plt.ylabel("Magnitude / Value")
            plt.grid(True, linestyle=':', alpha=0.7)
            plt.tight_layout()
            plt.show()

        else:
             print(f"\n⚠️ [{current_title}] Unhandled multi-dimensional array of shape {val_np.shape}")

# Example usage:
visualize_bridge2ai_features(extracted_data)

visualize_and_print_features(extracted_data)

### AUDIO PIPELINE
!pip install librosa soundfile pyloudnorm noisereduce matplotlib numpy scipy

"""
Bridge2AI-Voice Aligned Audio Preprocessing Pipeline
=====================================================
A quality gate + preprocessing pipeline for consumer voice recordings
that aligns with the Bridge2AI-Voice dataset standards.

Designed for Google Colab. Each step is its own function with before/after
visualization so you can see exactly what changes at every stage.

Recording Note (iOS):
    iOS does not record natively to .wav. The standard formats are:
    - .m4a (AAC compressed) via AVAudioRecorder
    - .caf (Core Audio Format, can be Linear PCM / uncompressed)
    You CAN configure AVAudioRecorder with kAudioFormatLinearPCM and write
    a .wav header manually, but the simplest path is:
      Record as .m4a → this pipeline converts to .wav in Step 1.
    If you use AVAudioEngine with LPCM output, record as .caf and this
    pipeline handles that too.

Usage in Colab:
    1. Run the install cell
    2. Upload an audio file (m4a, caf, mp3, webm, wav, etc.)
    3. Run the pipeline
"""

# =============================================================================
# CELL 1: Install Dependencies (run this cell first in Colab)
# =============================================================================
# !pip install librosa soundfile pyloudnorm noisereduce matplotlib numpy scipy

import os
import numpy as np
import librosa
import soundfile as sf
import pyloudnorm as pyln
import noisereduce as nr
import matplotlib.pyplot as plt
from scipy.signal import butter, sosfilt
from scipy.io import wavfile
from IPython.display import Audio, display, HTML
import warnings
import json
from dataclasses import dataclass, field, asdict
from typing import Optional, Tuple, List
import subprocess
import tempfile

warnings.filterwarnings('ignore')


# =============================================================================
# CONFIGURATION
# =============================================================================
@dataclass
class PipelineConfig:
    """All configurable thresholds in one place."""

    # Target sample rate: Bridge2AI preprocesses all audio to 16 kHz
    # Reference: PhysioNet B2AI-Voice v1.0-v3.0 documentation
    target_sr: int = 16000

    # Bit depth for output WAV
    bit_depth: int = 16

    # SNR thresholds (dB)
    # Reference: Deliyski et al. (2005) via ASHA Protocol (Patel et al., 2018)
    #   >= 42 dB: ideal (perturbation error < 1%)
    #   >= 30 dB: acceptable
    #   <  30 dB: reject
    snr_ideal: float = 42.0
    snr_acceptable: float = 30.0
    snr_reject: float = 30.0

    # Silence period: seconds of silence expected BEFORE the voice task
    # Reference: ASHA Protocol recommends ~5s of quiet for noise floor estimation
    silence_duration_sec: float = 3.0

    # Minimum voiced duration (seconds) after trimming
    # AVQI protocol extracts middle 3s from a 5s sustained vowel
    min_voiced_duration_sec: float = 3.0

    # Clipping: max fraction of samples at digital ceiling before rejection
    # Samples within this margin of ±1.0 are considered clipped
    clipping_margin: float = 0.001  # within 0.1% of full scale
    max_clipping_fraction: float = 0.001  # reject if > 0.1% of samples clipped

    # LUFS normalization target
    # EBU R128 broadcast standard; constant gain preserves SNR & amplitude ratios
    target_lufs: float = -23.0

    # Noise reduction: only applied in the 30-42 dB SNR "marginal" band
    # Stationary noise reduction strength (0.0 - 1.0)
    noise_reduce_strength: float = 0.7

    # Butterworth anti-aliasing filter order
    # Reference: B2AI uses Butterworth anti-aliasing before resampling
    butter_order: int = 8

    # Voice Activity Detection: energy-based threshold
    # Frame is "voiced" if its RMS energy > (noise_floor_rms * this multiplier)
    vad_energy_multiplier: float = 3.0
    vad_frame_length_ms: float = 25.0  # match B2AI spectrogram window
    vad_hop_length_ms: float = 10.0    # match B2AI spectrogram hop

    # ── Device / Microphone Compensation ──
    # Device identifier string passed from the recording app
    # e.g. "iPhone15,2" (iPhone 15 Pro), "SM-S928U" (Galaxy S25 Ultra)
    # Used to look up frequency response correction curves
    device_id: str = "unknown"

    # Whether to apply CMVN (Cepstral Mean and Variance Normalization)
    # Removes channel/microphone coloration from MFCC-based features
    # Standard technique in speech recognition for device independence
    apply_cmvn: bool = True

    # High-pass filter cutoff (Hz) to remove low-frequency mic roll-off
    # Phone MEMS mics typically roll off below 100-200 Hz at 6 dB/octave
    # B2AI headset mics are flat down to ~50 Hz
    # This filter standardizes the low-frequency behavior across devices
    highpass_cutoff_hz: float = 80.0
    highpass_order: int = 4

    # AGC detection sensitivity
    # If the standard deviation of frame-level RMS is abnormally low relative
    # to the mean, AGC is likely active (it compresses dynamic range)
    agc_coefficient_of_variation_threshold: float = 0.15


# =============================================================================
# PIPELINE REPORT
# =============================================================================
@dataclass
class QualityReport:
    """Collects all quality metrics and pass/fail decisions."""
    # Metadata
    input_file: str = ""
    input_format: str = ""
    input_sr: int = 0
    input_duration_sec: float = 0.0
    input_channels: int = 0

    # Quality gate results
    gate_silence_detected: bool = False
    gate_has_voice: bool = False
    gate_snr_db: float = 0.0
    gate_snr_verdict: str = ""  # "ideal", "acceptable", "marginal", "reject"
    gate_clipping_fraction: float = 0.0
    gate_clipping_pass: bool = False
    gate_min_duration_pass: bool = False
    gate_voiced_duration_sec: float = 0.0

    # Overall
    gate_passed: bool = False
    gate_failure_reasons: List[str] = field(default_factory=list)

    # Preprocessing applied
    noise_reduction_applied: bool = False
    mic_compensation_applied: bool = False
    cmvn_applied: bool = False
    agc_detected: bool = False
    agc_warning: str = ""
    device_id: str = "unknown"
    highpass_applied: bool = False
    lufs_before: float = 0.0
    lufs_after: float = 0.0
    output_sr: int = 0
    output_duration_sec: float = 0.0

    def summary(self) -> str:
        status = "PASSED" if self.gate_passed else "FAILED"
        lines = [
            f"{'='*60}",
            f"  QUALITY GATE: {status}",
            f"{'='*60}",
            f"  Input: {self.input_file}",
            f"  Format: {self.input_format} | {self.input_sr} Hz | {self.input_channels}ch | {self.input_duration_sec:.2f}s",
            f"  SNR: {self.gate_snr_db:.1f} dB → {self.gate_snr_verdict}",
            f"  Clipping: {self.gate_clipping_fraction*100:.3f}% → {'PASS' if self.gate_clipping_pass else 'FAIL'}",
            f"  Voice detected: {'Yes' if self.gate_has_voice else 'No'}",
            f"  Voiced duration: {self.gate_voiced_duration_sec:.2f}s → {'PASS' if self.gate_min_duration_pass else 'FAIL'}",
        ]
        if not self.gate_passed:
            lines.append(f"  Failure reasons: {', '.join(self.gate_failure_reasons)}")
        if self.agc_detected:
            lines.append(f"  ⚠ AGC detected: {self.agc_warning}")
        lines.append(f"  Device: {self.device_id}")
        if self.highpass_applied:
            lines.append(f"  High-pass filter: Applied (mic roll-off compensation)")
        if self.cmvn_applied:
            lines.append(f"  CMVN: Applied (channel normalization)")
        if self.noise_reduction_applied:
            lines.append(f"  Noise reduction: Applied (SNR was marginal)")
        lines.append(f"  LUFS: {self.lufs_before:.1f} → {self.lufs_after:.1f}")
        lines.append(f"  Output: {self.output_sr} Hz | {self.output_duration_sec:.2f}s")
        lines.append(f"{'='*60}")
        return "\n".join(lines)


# =============================================================================
# VISUALIZATION HELPERS
# =============================================================================
def plot_comparison(before: np.ndarray, after: np.ndarray,
                    sr_before: int, sr_after: int,
                    title: str, step_name: str):
    """Plot waveform + spectrogram before/after a processing step, with audio playback."""
    fig, axes = plt.subplots(2, 2, figsize=(14, 6))
    fig.suptitle(f"Step: {step_name}", fontsize=14, fontweight='bold')

    # Before waveform
    t_before = np.arange(len(before)) / sr_before
    axes[0, 0].plot(t_before, before, linewidth=0.3, color='#2196F3')
    axes[0, 0].set_title(f"Before — Waveform ({sr_before} Hz)")
    axes[0, 0].set_xlabel("Time (s)")
    axes[0, 0].set_ylabel("Amplitude")
    axes[0, 0].set_ylim(-1.05, 1.05)

    # After waveform
    t_after = np.arange(len(after)) / sr_after
    axes[0, 1].plot(t_after, after, linewidth=0.3, color='#4CAF50')
    axes[0, 1].set_title(f"After — Waveform ({sr_after} Hz)")
    axes[0, 1].set_xlabel("Time (s)")
    axes[0, 1].set_ylabel("Amplitude")
    axes[0, 1].set_ylim(-1.05, 1.05)

    # Before spectrogram
    S_before = librosa.feature.melspectrogram(y=before, sr=sr_before, n_mels=80)
    S_before_db = librosa.power_to_db(S_before, ref=np.max)
    librosa.display.specshow(S_before_db, sr=sr_before, x_axis='time',
                             y_axis='mel', ax=axes[1, 0], cmap='magma')
    axes[1, 0].set_title("Before — Mel Spectrogram")

    # After spectrogram
    S_after = librosa.feature.melspectrogram(y=after, sr=sr_after, n_mels=80)
    S_after_db = librosa.power_to_db(S_after, ref=np.max)
    librosa.display.specshow(S_after_db, sr=sr_after, x_axis='time',
                             y_axis='mel', ax=axes[1, 1], cmap='magma')
    axes[1, 1].set_title("After — Mel Spectrogram")

    plt.tight_layout()
    plt.show()

    # Audio playback: before and after
    print(f"    🔊 Before:")
    display(Audio(before, rate=sr_before))
    print(f"    🔊 After:")
    display(Audio(after, rate=sr_after))


def plot_snr_analysis(audio: np.ndarray, sr: int, silence_end_sample: int,
                      snr_db: float, config: PipelineConfig):
    """Visualize the silence vs. voiced regions used for SNR calculation."""
    fig, ax = plt.subplots(1, 1, figsize=(14, 3))
    t = np.arange(len(audio)) / sr

    ax.plot(t, audio, linewidth=0.3, color='#607D8B', alpha=0.7)

    silence_end_time = silence_end_sample / sr
    ax.axvspan(0, silence_end_time, alpha=0.2, color='red', label='Noise estimation region')
    ax.axvspan(silence_end_time, t[-1], alpha=0.1, color='green', label='Signal region')
    ax.axvline(x=silence_end_time, color='red', linestyle='--', linewidth=1)

    verdict_color = '#4CAF50' if snr_db >= config.snr_ideal else (
        '#FF9800' if snr_db >= config.snr_acceptable else '#F44336')
    ax.set_title(f"SNR Analysis: {snr_db:.1f} dB", fontsize=12,
                 fontweight='bold', color=verdict_color)
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Amplitude")
    ax.legend(loc='upper right')
    plt.tight_layout()
    plt.show()


def plot_vad(audio: np.ndarray, sr: int, voiced_mask: np.ndarray,
             frame_length: int, hop_length: int):
    """Visualize which frames were detected as voiced."""
    fig, ax = plt.subplots(1, 1, figsize=(14, 3))
    t = np.arange(len(audio)) / sr
    ax.plot(t, audio, linewidth=0.3, color='#607D8B', alpha=0.5)

    # Overlay voiced regions
    for i, is_voiced in enumerate(voiced_mask):
        if is_voiced:
            start = i * hop_length / sr
            end = (i * hop_length + frame_length) / sr
            ax.axvspan(start, end, alpha=0.15, color='green')

    voiced_pct = np.mean(voiced_mask) * 100
    ax.set_title(f"Voice Activity Detection: {voiced_pct:.1f}% of frames voiced",
                 fontsize=12, fontweight='bold')
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Amplitude")
    plt.tight_layout()
    plt.show()


# =============================================================================
# STEP 0: LOAD & CONVERT TO WAV
# =============================================================================
def step0_load_audio(input_path: str, config: PipelineConfig) -> Tuple[np.ndarray, int, QualityReport]:
    """
    Load any audio format and convert to mono float32 numpy array.

    iOS recording formats:
      - .m4a (AAC) — most common from AVAudioRecorder
      - .caf (Core Audio Format) — from AVAudioEngine with LPCM
      - .wav — possible but not native iOS default

    This step uses librosa which handles m4a, caf, mp3, webm, ogg, flac, wav
    via ffmpeg backend.

    Bridge2AI reference:
      Raw audio was preprocessed by converting to monaural.
    """
    report = QualityReport()
    report.input_file = os.path.basename(input_path)
    report.input_format = os.path.splitext(input_path)[1].lower()

    # Load at native sample rate, mono
    audio, sr = librosa.load(input_path, sr=None, mono=True)

    report.input_sr = sr
    report.input_duration_sec = len(audio) / sr
    report.input_channels = 1  # forced mono by librosa

    print(f"[Step 0] Loaded: {report.input_file}")
    print(f"         Format: {report.input_format} | {sr} Hz | {report.input_duration_sec:.2f}s")
    print(f"         Converted to: mono float32 numpy array")

    return audio, sr, report


# =============================================================================
# QUALITY GATE 1: SILENCE REGION DETECTION
# =============================================================================
def gate1_check_silence_region(audio: np.ndarray, sr: int,
                                config: PipelineConfig) -> Tuple[bool, int]:
    """
    Verify that the recording begins with a silence period for noise estimation.

    The ASHA Protocol (Patel et al., 2018) recommends recording ~5 seconds of
    quiet before phonation to establish the noise floor. We check for at least
    config.silence_duration_sec seconds of low-energy audio at the start.

    Returns:
        (has_silence_region, silence_end_sample)
    """
    silence_samples = int(config.silence_duration_sec * sr)

    if len(audio) < silence_samples:
        print(f"[Gate 1] FAIL: Recording too short for silence region analysis")
        return False, 0

    # Check that the first N seconds are significantly quieter than the rest
    silence_region = audio[:silence_samples]
    signal_region = audio[silence_samples:]

    if len(signal_region) == 0:
        print(f"[Gate 1] FAIL: No audio after silence region")
        return False, 0

    silence_rms = np.sqrt(np.mean(silence_region ** 2)) + 1e-10
    signal_rms = np.sqrt(np.mean(signal_region ** 2)) + 1e-10

    ratio_db = 20 * np.log10(signal_rms / silence_rms)

    # The signal region should be noticeably louder than the silence region
    has_silence = ratio_db > 10  # at least 10 dB difference

    status = "PASS" if has_silence else "WARN"
    print(f"[Gate 1] Silence region check: {status}")
    print(f"         Silence RMS: {silence_rms:.6f} | Signal RMS: {signal_rms:.6f}")
    print(f"         Signal-to-silence ratio: {ratio_db:.1f} dB")

    if not has_silence:
        print(f"         WARNING: First {config.silence_duration_sec}s not clearly silent.")
        print(f"         SNR estimation may be unreliable.")

    return has_silence, silence_samples


# =============================================================================
# QUALITY GATE 2: SNR CHECK
# =============================================================================
def gate2_check_snr(audio: np.ndarray, sr: int, silence_end_sample: int,
                    config: PipelineConfig, report: QualityReport) -> Tuple[str, float]:
    """
    Compute Signal-to-Noise Ratio using the silence region as noise estimate.

    Thresholds (Deliyski et al., 2005 / ASHA Protocol):
      >= 42 dB: ideal — perturbation measurement error < 1%
      >= 30 dB: acceptable
      <  30 dB: reject

    Returns:
        (verdict, snr_db) where verdict is "ideal", "acceptable", "marginal", or "reject"
    """
    noise_region = audio[:silence_end_sample]
    signal_region = audio[silence_end_sample:]

    noise_power = np.mean(noise_region ** 2) + 1e-20
    signal_power = np.mean(signal_region ** 2) + 1e-20

    snr_db = 10 * np.log10(signal_power / noise_power)

    if snr_db >= config.snr_ideal:
        verdict = "ideal"
    elif snr_db >= config.snr_acceptable:
        verdict = "acceptable"
    else:
        verdict = "reject"

    report.gate_snr_db = snr_db
    report.gate_snr_verdict = verdict

    color_map = {"ideal": "🟢", "acceptable": "🟡", "reject": "🔴"}
    print(f"[Gate 2] SNR: {snr_db:.1f} dB → {color_map[verdict]} {verdict.upper()}")
    print(f"         Thresholds: ≥42 dB ideal | ≥30 dB acceptable | <30 dB reject")

    plot_snr_analysis(audio, sr, silence_end_sample, snr_db, config)

    return verdict, snr_db


# =============================================================================
# QUALITY GATE 3: CLIPPING DETECTION
# =============================================================================
def gate3_check_clipping(audio: np.ndarray, config: PipelineConfig,
                          report: QualityReport) -> bool:
    """
    Detect digital clipping — samples at or near the absolute digital ceiling.

    Clipping corrupts perturbation measures (jitter, shimmer) and spectral
    features. We flag if more than 0.1% of samples are within 0.1% of ±1.0.

    Note: B2AI avoids clipping via hardware (headset mic at fixed distance).
    For consumer recordings without controlled gain, this check is essential.
    """
    clipped = np.abs(audio) >= (1.0 - config.clipping_margin)
    clipping_fraction = np.mean(clipped)

    passed = clipping_fraction <= config.max_clipping_fraction
    report.gate_clipping_fraction = clipping_fraction
    report.gate_clipping_pass = passed

    status = "PASS" if passed else "FAIL"
    print(f"[Gate 3] Clipping: {clipping_fraction*100:.4f}% of samples clipped → {status}")
    print(f"         Threshold: ≤{config.max_clipping_fraction*100:.2f}%")

    if not passed:
        # Show where clipping occurs
        fig, ax = plt.subplots(1, 1, figsize=(14, 2))
        t = np.arange(len(audio)) / 16000  # approximate for display
        ax.plot(t, audio, linewidth=0.3, color='#607D8B')
        clip_indices = np.where(clipped)[0]
        if len(clip_indices) > 0:
            ax.scatter(clip_indices / 16000, audio[clip_indices],
                      color='red', s=1, zorder=5, label='Clipped samples')
        ax.axhline(y=1.0 - config.clipping_margin, color='red', linestyle='--',
                   alpha=0.5, linewidth=0.8)
        ax.axhline(y=-(1.0 - config.clipping_margin), color='red', linestyle='--',
                   alpha=0.5, linewidth=0.8)
        ax.set_title("Clipping Detection", fontweight='bold')
        ax.set_xlabel("Time (s)")
        ax.legend()
        plt.tight_layout()
        plt.show()

    return passed


# =============================================================================
# QUALITY GATE 4: VOICE ACTIVITY DETECTION
# =============================================================================
def gate4_check_voice_activity(audio: np.ndarray, sr: int,
                                silence_end_sample: int,
                                config: PipelineConfig,
                                report: QualityReport) -> Tuple[bool, float]:
    """
    Energy-based Voice Activity Detection to confirm the user actually spoke.

    Uses frame-level RMS energy compared against the noise floor estimated
    from the silence region. Frame parameters match B2AI spectrogram settings:
    25ms window, 10ms hop.

    Returns:
        (has_voice, voiced_duration_sec)
    """
    frame_length = int(config.vad_frame_length_ms * sr / 1000)
    hop_length = int(config.vad_hop_length_ms * sr / 1000)

    # Estimate noise floor from silence region
    noise_region = audio[:silence_end_sample]
    noise_rms = np.sqrt(np.mean(noise_region ** 2)) + 1e-10
    energy_threshold = noise_rms * config.vad_energy_multiplier

    # Compute per-frame RMS for the signal region
    signal_region = audio[silence_end_sample:]
    n_frames = max(1, (len(signal_region) - frame_length) // hop_length + 1)

    voiced_mask = np.zeros(n_frames, dtype=bool)
    for i in range(n_frames):
        start = i * hop_length
        end = start + frame_length
        if end > len(signal_region):
            break
        frame_rms = np.sqrt(np.mean(signal_region[start:end] ** 2))
        voiced_mask[i] = frame_rms > energy_threshold

    voiced_duration = np.sum(voiced_mask) * (hop_length / sr)
    has_voice = voiced_duration >= config.min_voiced_duration_sec

    report.gate_has_voice = np.any(voiced_mask)
    report.gate_voiced_duration_sec = voiced_duration
    report.gate_min_duration_pass = has_voice

    status = "PASS" if has_voice else "FAIL"
    print(f"[Gate 4] Voice activity: {voiced_duration:.2f}s voiced → {status}")
    print(f"         Minimum required: {config.min_voiced_duration_sec}s")
    print(f"         Noise floor RMS: {noise_rms:.6f} | Threshold: {energy_threshold:.6f}")

    plot_vad(signal_region, sr, voiced_mask, frame_length, hop_length)

    return has_voice, voiced_duration


# =============================================================================
# QUALITY GATE 5: AGC (AUTOMATIC GAIN CONTROL) DETECTION
# =============================================================================
def gate5_check_agc(audio: np.ndarray, sr: int,
                    silence_end_sample: int,
                    config: PipelineConfig,
                    report: QualityReport) -> bool:
    """
    Detect whether Automatic Gain Control (AGC) is active on the recording.

    WHY THIS MATTERS:
    iOS and Android audio stacks can apply AGC at the hardware/driver level
    before your app sees the samples. AGC dynamically adjusts gain frame-by-frame,
    which directly corrupts amplitude-dependent voice biomarkers:
      - Shimmer (cycle-to-cycle amplitude variation) is distorted
      - HNR (harmonics-to-noise ratio) is altered
      - Intensity contours are compressed
      - L/H spectral ratio can shift

    Bridge2AI avoids this by using a headset microphone at fixed distance in a
    controlled environment — AGC has little to do when the input level is stable.

    DETECTION METHOD:
    In natural speech, voiced segments have substantial amplitude variation
    (prosodic stress, loudness changes, etc.). AGC compresses this variation,
    producing unnaturally uniform frame-level energy. We detect this by computing
    the coefficient of variation (std/mean) of frame-level RMS energy across
    voiced segments. If CV is abnormally low, AGC is likely active.

    This is a WARNING, not a hard rejection — the recording can still be used,
    but amplitude-dependent features should be interpreted with caution.

    Returns:
        True if AGC is likely NOT active (good), False if AGC detected (warning)
    """
    print(f"[Gate 5] AGC (Automatic Gain Control) Detection")

    signal_region = audio[silence_end_sample:]
    if len(signal_region) < sr:
        print(f"         Signal too short for AGC analysis. Skipping.")
        return True

    # Compute frame-level RMS energy
    frame_length = int(config.vad_frame_length_ms * sr / 1000)
    hop_length = int(config.vad_hop_length_ms * sr / 1000)
    n_frames = (len(signal_region) - frame_length) // hop_length + 1

    frame_rms = np.zeros(n_frames)
    for i in range(n_frames):
        start = i * hop_length
        end = start + frame_length
        frame_rms[i] = np.sqrt(np.mean(signal_region[start:end] ** 2))

    # Only analyze frames with actual voice (above noise floor)
    noise_rms = np.sqrt(np.mean(audio[:silence_end_sample] ** 2)) + 1e-10
    voiced_rms = frame_rms[frame_rms > noise_rms * config.vad_energy_multiplier]

    if len(voiced_rms) < 10:
        print(f"         Not enough voiced frames for AGC analysis. Skipping.")
        return True

    # Coefficient of variation: std / mean
    cv = np.std(voiced_rms) / (np.mean(voiced_rms) + 1e-10)

    agc_likely = cv < config.agc_coefficient_of_variation_threshold
    report.agc_detected = agc_likely

    if agc_likely:
        report.agc_warning = (
            f"CV={cv:.3f} < {config.agc_coefficient_of_variation_threshold} — "
            f"amplitude variation is abnormally low, suggesting AGC is active. "
            f"Shimmer, HNR, and intensity features may be unreliable."
        )
        print(f"         ⚠ WARNING: AGC likely active (CV={cv:.3f})")
        print(f"         Voiced RMS variation is abnormally uniform.")
        print(f"         Amplitude-dependent features (shimmer, HNR) may be distorted.")
        print(f"         Recommendation: disable AGC in your iOS/Android recording config.")
        print(f"         iOS: set AVAudioSession mode to .measurement")
        print(f"         Android: use VOICE_RECOGNITION source or disable NOISE_SUPPRESSOR")
    else:
        print(f"         PASS: No AGC detected (CV={cv:.3f})")
        print(f"         Amplitude variation is within normal range.")

    # Visualization
    fig, axes = plt.subplots(1, 2, figsize=(14, 3))

    # Frame-level RMS over time
    t_frames = np.arange(n_frames) * hop_length / sr
    axes[0].plot(t_frames, frame_rms, linewidth=0.5, color='#2196F3', alpha=0.7)
    axes[0].axhline(y=noise_rms * config.vad_energy_multiplier,
                    color='red', linestyle='--', linewidth=0.8, label='Voice threshold')
    axes[0].set_title("Frame-level RMS Energy", fontweight='bold')
    axes[0].set_xlabel("Time (s)")
    axes[0].set_ylabel("RMS")
    axes[0].legend()

    # Histogram of voiced frame energies
    color = '#F44336' if agc_likely else '#4CAF50'
    axes[1].hist(voiced_rms, bins=30, color=color, alpha=0.7, edgecolor='white')
    axes[1].axvline(x=np.mean(voiced_rms), color='black', linestyle='--',
                    linewidth=1, label=f'Mean={np.mean(voiced_rms):.4f}')
    axes[1].set_title(f"Voiced Frame RMS Distribution (CV={cv:.3f})", fontweight='bold')
    axes[1].set_xlabel("RMS Energy")
    axes[1].set_ylabel("Count")
    axes[1].legend()

    plt.tight_layout()
    plt.show()

    return not agc_likely


# =============================================================================
# QUALITY GATE: AGGREGATE DECISION
# =============================================================================
def run_quality_gate(audio: np.ndarray, sr: int, config: PipelineConfig,
                     report: QualityReport) -> Tuple[bool, int]:
    """
    Run all quality gates and return aggregate pass/fail.

    Returns:
        (passed, silence_end_sample)
    """
    print(f"\n{'='*60}")
    print(f"  QUALITY GATE")
    print(f"{'='*60}\n")

    failures = []

    # Gate 1: Silence region
    has_silence, silence_end_sample = gate1_check_silence_region(audio, sr, config)
    report.gate_silence_detected = has_silence
    if not has_silence:
        # Use a default split if no clear silence region
        silence_end_sample = int(config.silence_duration_sec * sr)
        if silence_end_sample >= len(audio):
            silence_end_sample = len(audio) // 4
        print(f"         Using default silence region: first {silence_end_sample/sr:.1f}s")
    print()

    # Gate 2: SNR
    snr_verdict, snr_db = gate2_check_snr(audio, sr, silence_end_sample, config, report)
    if snr_verdict == "reject":
        failures.append(f"SNR too low ({snr_db:.1f} dB < {config.snr_reject} dB)")
    print()

    # Gate 3: Clipping
    clipping_ok = gate3_check_clipping(audio, config, report)
    if not clipping_ok:
        failures.append(f"Clipping detected ({report.gate_clipping_fraction*100:.3f}%)")
    print()

    # Gate 4: Voice activity
    has_voice, voiced_dur = gate4_check_voice_activity(
        audio, sr, silence_end_sample, config, report)
    if not has_voice:
        failures.append(f"Insufficient voiced audio ({voiced_dur:.2f}s < {config.min_voiced_duration_sec}s)")
    print()

    # Gate 5: AGC detection (warning only, does not cause rejection)
    agc_ok = gate5_check_agc(audio, sr, silence_end_sample, config, report)
    if not agc_ok:
        print(f"         (AGC is a warning, not a hard rejection)")
    print()

    passed = len(failures) == 0
    report.gate_passed = passed
    report.gate_failure_reasons = failures

    status = "✅ PASSED" if passed else "❌ FAILED"
    print(f"{'='*60}")
    print(f"  Quality Gate Result: {status}")
    if failures:
        for f in failures:
            print(f"    ✗ {f}")
    print(f"{'='*60}\n")

    return passed, silence_end_sample


# =============================================================================
# STEP 1: RESAMPLE TO 16 kHz WITH BUTTERWORTH ANTI-ALIAS
# =============================================================================
def step1_resample(audio: np.ndarray, sr: int,
                   config: PipelineConfig) -> Tuple[np.ndarray, int]:
    """
    Resample to 16 kHz with Butterworth anti-aliasing filter.

    Bridge2AI reference (PhysioNet v1.0-v3.0):
      "Raw audio was preprocessed by converting to monaural and resampling
       to 16 kHz with a Butterworth anti-aliasing filter applied."

    The Butterworth filter is applied BEFORE downsampling to prevent aliasing.
    Cutoff is set at the new Nyquist frequency (8 kHz).
    """
    print(f"[Step 1] Resample: {sr} Hz → {config.target_sr} Hz")

    before = audio.copy()
    before_sr = sr

    if sr == config.target_sr:
        print(f"         Already at target sample rate. No resampling needed.")
        return audio, sr

    if sr > config.target_sr:
        # Apply Butterworth low-pass anti-aliasing filter before downsampling
        nyquist_new = config.target_sr / 2
        nyquist_old = sr / 2
        normalized_cutoff = nyquist_new / nyquist_old

        # Clamp to valid range (0, 1) exclusive
        normalized_cutoff = min(normalized_cutoff, 0.9999)

        sos = butter(config.butter_order, normalized_cutoff, btype='low', output='sos')
        audio_filtered = sosfilt(sos, audio).astype(np.float32)

        print(f"         Applied order-{config.butter_order} Butterworth LPF, cutoff={nyquist_new:.0f} Hz")
    else:
        audio_filtered = audio
        print(f"         Upsampling from {sr} Hz (no anti-alias filter needed)")

    # Resample using librosa (high-quality polyphase resampling)
    audio_resampled = librosa.resample(audio_filtered, orig_sr=sr, target_sr=config.target_sr)

    print(f"         Samples: {len(before)} → {len(audio_resampled)}")
    print(f"         Duration preserved: {len(before)/sr:.3f}s → {len(audio_resampled)/config.target_sr:.3f}s")

    plot_comparison(before, audio_resampled, before_sr, config.target_sr,
                    f"Resample {sr}→{config.target_sr} Hz", "1: Resample to 16 kHz")

    return audio_resampled, config.target_sr


# =============================================================================
# STEP 2: HIGH-PASS FILTER (MICROPHONE ROLL-OFF COMPENSATION)
# =============================================================================
def step2_highpass_filter(audio: np.ndarray, sr: int,
                          config: PipelineConfig,
                          report: QualityReport) -> np.ndarray:
    """
    Apply a high-pass Butterworth filter to compensate for MEMS mic roll-off.

    WHY THIS IS NEEDED:
    Phone MEMS microphones (the tiny mics in iPhones, Androids, etc.) have a
    fundamentally different low-frequency response than the headset and research
    condenser microphones used by Bridge2AI. Specifically:

      - Research mics (GRAS 40AF, AKG C520): flat response down to 20-50 Hz
      - Headset mics (B2AI recommended): flat down to ~50-80 Hz
      - Phone MEMS mics: roll off below 100-200 Hz at ~6 dB/octave

    This roll-off varies by device:
      - iPhone MEMS: typically -3dB at ~80-100 Hz
      - Samsung Galaxy MEMS: varies, often -3dB at ~100-150 Hz
      - Budget Android: can roll off as high as 200 Hz

    The Bridge2AI validation study (Awan et al., 2024) found a "strong device
    effect on L/H Ratio" directly attributable to these frequency response
    differences between microphones.

    WHAT THIS FILTER DOES:
    Rather than trying to boost the low frequencies (which would also amplify
    noise), we standardize ALL recordings to the same low-frequency behavior
    by applying a consistent high-pass filter. This removes the variable
    low-frequency content that differs between devices, creating a level
    playing field.

    The cutoff (default 80 Hz) is set at the approximate -3dB point of
    B2AI's recommended headset microphones. Content below 80 Hz is:
      - Not needed for F0 (adult speech F0 range: ~85-300 Hz)
      - Dominated by room rumble, HVAC, handling noise
      - The primary source of device-to-device variability

    After this filter, a recording from an iPhone and a Galaxy will have
    much more similar spectral tilt characteristics.
    """
    print(f"[Step 2] High-pass filter: {config.highpass_cutoff_hz} Hz "
          f"(microphone roll-off compensation)")

    before = audio.copy()

    # Design Butterworth high-pass filter
    nyquist = sr / 2
    normalized_cutoff = config.highpass_cutoff_hz / nyquist

    if normalized_cutoff >= 1.0:
        print(f"         WARNING: Cutoff {config.highpass_cutoff_hz} Hz >= Nyquist {nyquist} Hz. Skipping.")
        return audio

    sos = butter(config.highpass_order, normalized_cutoff, btype='high', output='sos')
    audio_filtered = sosfilt(sos, audio).astype(np.float32)

    report.highpass_applied = True
    report.device_id = config.device_id

    print(f"         Device: {config.device_id}")
    print(f"         Cutoff: {config.highpass_cutoff_hz} Hz, order {config.highpass_order}")
    print(f"         Purpose: Remove variable low-freq content that differs between")
    print(f"         phone mics, standardizing to B2AI headset mic behavior (~80 Hz)")

    # Show frequency response comparison
    fig, axes = plt.subplots(1, 3, figsize=(16, 3.5))

    # Before/after waveform (zoomed to see the difference)
    show_samples = min(len(before), int(0.1 * sr))  # show 100ms
    t = np.arange(show_samples) / sr * 1000  # ms
    axes[0].plot(t, before[:show_samples], linewidth=0.5, color='#2196F3',
                 alpha=0.7, label='Before')
    axes[0].plot(t, audio_filtered[:show_samples], linewidth=0.5, color='#4CAF50',
                 alpha=0.7, label='After')
    axes[0].set_title("Waveform (first 100ms)", fontweight='bold')
    axes[0].set_xlabel("Time (ms)")
    axes[0].legend()

    # Spectrum comparison
    n_fft = 2048
    S_before = np.abs(np.fft.rfft(before[:n_fft]))
    S_after = np.abs(np.fft.rfft(audio_filtered[:n_fft]))
    freqs = np.fft.rfftfreq(n_fft, 1/sr)

    axes[1].semilogy(freqs, S_before + 1e-10, linewidth=0.8, color='#2196F3',
                     alpha=0.7, label='Before')
    axes[1].semilogy(freqs, S_after + 1e-10, linewidth=0.8, color='#4CAF50',
                     alpha=0.7, label='After')
    axes[1].axvline(x=config.highpass_cutoff_hz, color='red', linestyle='--',
                    linewidth=1, label=f'Cutoff: {config.highpass_cutoff_hz} Hz')
    axes[1].set_title("Frequency Spectrum", fontweight='bold')
    axes[1].set_xlabel("Frequency (Hz)")
    axes[1].set_ylabel("Magnitude")
    axes[1].set_xlim(0, 2000)
    axes[1].legend()

    # Filter frequency response
    from scipy.signal import sosfreqz
    w, h = sosfreqz(sos, worN=2048, fs=sr)
    axes[2].plot(w, 20 * np.log10(np.abs(h) + 1e-10), linewidth=1.5, color='#FF5722')
    axes[2].axvline(x=config.highpass_cutoff_hz, color='red', linestyle='--',
                    linewidth=1, label=f'Cutoff: {config.highpass_cutoff_hz} Hz')
    axes[2].axhline(y=-3, color='gray', linestyle=':', linewidth=0.8, label='-3 dB')
    axes[2].set_title("High-pass Filter Response", fontweight='bold')
    axes[2].set_xlabel("Frequency (Hz)")
    axes[2].set_ylabel("Gain (dB)")
    axes[2].set_xlim(0, 2000)
    axes[2].set_ylim(-40, 5)
    axes[2].legend()

    plt.tight_layout()
    plt.show()

    # Audio playback: before and after
    print(f"    🔊 Before high-pass:")
    display(Audio(before, rate=sr))
    print(f"    🔊 After high-pass:")
    display(Audio(audio_filtered, rate=sr))

    return audio_filtered
def step3_cmvn_compensation(audio: np.ndarray, sr: int,
                             config: PipelineConfig,
                             report: QualityReport) -> np.ndarray:
    """
    Apply Cepstral Mean and Variance Normalization to remove channel effects.

    WHY THIS IS NEEDED:
    Even after the high-pass filter, different microphones impose different
    spectral "coloring" on the signal — a slight emphasis here, a dip there.
    This coloring is roughly constant across the recording (it's a property
    of the microphone hardware, not the speaker's voice). CMVN removes it.

    HOW IT WORKS:
    CMVN operates in the cepstral domain (on MFCCs or log-mel features):
      1. Compute the mean cepstral vector across all frames in the utterance
      2. Subtract the mean from each frame (CMN — removes channel bias)
      3. Optionally normalize variance to unit (CVN — removes channel scaling)

    This is the standard technique in speech recognition (used in Kaldi, ESPnet,
    etc.) for making models device-independent. It works because:
      - The microphone's frequency response adds a constant offset in the
        log-spectral / cepstral domain
      - Subtracting the mean removes this constant offset
      - The speaker's voice characteristics (F0, formant *ratios*, perturbation)
        are preserved because they vary frame-to-frame

    IMPORTANT: CMVN is applied to the FEATURES, not the raw audio waveform.
    However, we implement an equivalent time-domain operation here: spectral
    flattening via mean log-spectrum subtraction, which achieves the same
    effect while keeping the output as a waveform for downstream compatibility.

    For your feature extraction pipeline: if your feature extractor already
    applies CMVN (many do by default), you can skip this step to avoid
    double-normalization. Set config.apply_cmvn = False.
    """
    print(f"[Step 3] CMVN — Channel/Microphone Normalization")

    if not config.apply_cmvn:
        print(f"         Skipped (config.apply_cmvn = False)")
        print(f"         Make sure your feature extractor applies CMVN internally.")
        report.cmvn_applied = False
        return audio

    before = audio.copy()

    # Compute STFT
    n_fft = 512
    hop_length = int(config.vad_hop_length_ms * sr / 1000)  # 10ms hop
    S = librosa.stft(audio, n_fft=n_fft, hop_length=hop_length)
    magnitude = np.abs(S)
    phase = np.angle(S)

    # Compute mean log-magnitude spectrum (channel estimate)
    log_mag = np.log(magnitude + 1e-10)
    mean_log_spectrum = np.mean(log_mag, axis=1, keepdims=True)

    # Subtract mean log-spectrum (removes constant channel coloration)
    log_mag_normalized = log_mag - mean_log_spectrum

    # Optional: variance normalization
    std_log_spectrum = np.std(log_mag, axis=1, keepdims=True) + 1e-10
    log_mag_normalized = log_mag_normalized / std_log_spectrum

    # Reconstruct
    magnitude_normalized = np.exp(log_mag_normalized)
    S_normalized = magnitude_normalized * np.exp(1j * phase)
    audio_cmvn = librosa.istft(S_normalized, hop_length=hop_length, length=len(audio))
    audio_cmvn = audio_cmvn.astype(np.float32)

    # Preserve original peak level
    peak_before = np.max(np.abs(before))
    peak_after = np.max(np.abs(audio_cmvn))
    if peak_after > 0:
        audio_cmvn = audio_cmvn * (peak_before / peak_after)

    report.cmvn_applied = True

    print(f"         Applied spectral mean and variance normalization")
    print(f"         This removes microphone-specific frequency coloring")
    print(f"         so an iPhone recording and Galaxy recording produce")
    print(f"         more similar spectral features.")

    # Visualization: before/after mean spectrum
    fig, axes = plt.subplots(1, 2, figsize=(14, 3.5))

    S_before_mel = librosa.feature.melspectrogram(y=before, sr=sr, n_mels=80)
    S_after_mel = librosa.feature.melspectrogram(y=audio_cmvn, sr=sr, n_mels=80)

    mean_mel_before = np.mean(librosa.power_to_db(S_before_mel), axis=1)
    mean_mel_after = np.mean(librosa.power_to_db(S_after_mel), axis=1)

    mel_freqs = librosa.mel_frequencies(n_mels=80, fmin=0, fmax=sr/2)

    axes[0].plot(mel_freqs, mean_mel_before, linewidth=1.5, color='#2196F3',
                 label='Before CMVN')
    axes[0].plot(mel_freqs, mean_mel_after, linewidth=1.5, color='#4CAF50',
                 label='After CMVN')
    axes[0].set_title("Mean Mel Spectrum (channel shape removed)", fontweight='bold')
    axes[0].set_xlabel("Frequency (Hz)")
    axes[0].set_ylabel("Power (dB)")
    axes[0].legend()

    # Show the estimated channel response that was removed
    channel_estimate_db = 20 * np.log10(np.exp(mean_log_spectrum.flatten()) + 1e-10)
    freqs_fft = np.linspace(0, sr/2, len(channel_estimate_db))
    axes[1].plot(freqs_fft, channel_estimate_db, linewidth=1.5, color='#FF5722')
    axes[1].set_title("Estimated Channel Response (removed)", fontweight='bold')
    axes[1].set_xlabel("Frequency (Hz)")
    axes[1].set_ylabel("Magnitude (dB)")
    axes[1].axhline(y=0, color='gray', linestyle='--', linewidth=0.8)

    plt.tight_layout()
    plt.show()

    # Audio playback: before and after
    print(f"    🔊 Before CMVN:")
    display(Audio(before, rate=sr))
    print(f"    🔊 After CMVN:")
    display(Audio(audio_cmvn, rate=sr))

    return audio_cmvn
def step4_normalize_lufs(audio: np.ndarray, sr: int,
                          config: PipelineConfig,
                          report: QualityReport) -> np.ndarray:
    """
    Normalize loudness to a consistent LUFS target using EBU R128.

    This applies a CONSTANT GAIN across the entire signal, which:
      ✓ Preserves SNR (signal and noise scaled equally)
      ✓ Preserves relative amplitude dynamics
      ✓ Preserves shimmer, jitter, HNR ratios
      ✗ Does NOT compress dynamic range (unlike AGC)

    This is mathematically equivalent to the user being at a slightly
    different distance from the microphone — a linear operation.

    Target: -23 LUFS (EBU R128 broadcast standard)
    """
    print(f"[Step 4] LUFS Normalization → target: {config.target_lufs} LUFS")

    before = audio.copy()

    meter = pyln.Meter(sr)
    loudness_before = meter.integrated_loudness(audio)
    report.lufs_before = loudness_before

    print(f"         Before: {loudness_before:.1f} LUFS")

    # Apply constant gain normalization
    audio_normalized = pyln.normalize.loudness(audio, loudness_before, config.target_lufs)

    # Prevent any clipping from the gain increase
    peak = np.max(np.abs(audio_normalized))
    if peak > 0.99:
        audio_normalized = audio_normalized * (0.99 / peak)
        print(f"         Peak limiter applied (peak was {peak:.4f})")

    loudness_after = meter.integrated_loudness(audio_normalized)
    report.lufs_after = loudness_after
    gain_applied = loudness_after - loudness_before

    print(f"         After: {loudness_after:.1f} LUFS (gain: {gain_applied:+.1f} dB)")
    print(f"         This is a constant gain — SNR and amplitude ratios preserved.")

    plot_comparison(before, audio_normalized, sr, sr,
                    f"LUFS: {loudness_before:.1f} → {loudness_after:.1f}",
                    "4: LUFS Normalization (constant gain)")

    return audio_normalized


# =============================================================================
# STEP 5: CONDITIONAL NOISE REDUCTION (MARGINAL SNR ONLY)
# =============================================================================
def step5_conditional_noise_reduction(audio: np.ndarray, sr: int,
                                       snr_verdict: str,
                                       silence_end_sample_resampled: int,
                                       config: PipelineConfig,
                                       report: QualityReport) -> np.ndarray:
    """
    Apply minimal spectral gating noise reduction ONLY if SNR is marginal (30-42 dB).

    Bridge2AI philosophy: prevent noise at source (headset mic), don't clean algorithmically.
    But for consumer apps without guaranteed headsets, we need a pragmatic fallback:
      >= 42 dB: don't touch it
      30-42 dB: light spectral gating using noise profile from silence region, flag as processed
      <  30 dB: already rejected by quality gate

    Uses stationary noise reduction with the noise profile estimated from
    the silence period captured at the start of the recording.
    """
    print(f"[Step 5] Conditional Noise Reduction (SNR verdict: {snr_verdict})")

    if snr_verdict == "ideal":
        print(f"         SNR is ideal (≥42 dB). No noise reduction applied.")
        print(f"         (Matches B2AI approach: clean recordings need no processing)")
        report.noise_reduction_applied = False
        return audio

    # snr_verdict is "acceptable" — apply light noise reduction
    print(f"         SNR is acceptable but not ideal. Applying light spectral gating...")

    before = audio.copy()

    # Use silence region as noise profile
    # Adjust silence_end_sample for the resampled audio
    noise_clip = audio[:silence_end_sample_resampled]

    if len(noise_clip) < sr // 4:  # need at least 0.25s for good noise estimate
        print(f"         WARNING: Noise clip too short ({len(noise_clip)/sr:.2f}s). Skipping.")
        report.noise_reduction_applied = False
        return audio

    audio_cleaned = nr.reduce_noise(
        y=audio,
        sr=sr,
        y_noise=noise_clip,
        prop_decrease=config.noise_reduce_strength,
        stationary=True,  # assume stationary noise (HVAC, hum, etc.)
        n_fft=512,
        hop_length=int(config.vad_hop_length_ms * sr / 1000),
    )

    report.noise_reduction_applied = True
    print(f"         Noise reduction applied (strength: {config.noise_reduce_strength})")
    print(f"         ⚠ Recording flagged as algorithmically processed")

    plot_comparison(before, audio_cleaned, sr, sr,
                    "Spectral gating noise reduction",
                    "5: Conditional Noise Reduction")

    return audio_cleaned


# =============================================================================
# STEP 6: TRIM SILENCE REGION (OUTPUT VOICE ONLY)
# =============================================================================
def step6_trim_silence(audio: np.ndarray, sr: int,
                        silence_end_sample: int) -> np.ndarray:
    """
    Remove the leading silence region from the final output.

    The silence was needed for SNR estimation but should not be in the
    output file that goes to feature extraction. B2AI feature extraction
    operates on voice segments, not silence.
    """
    print(f"[Step 6] Trim leading silence region")

    before = audio.copy()
    audio_trimmed = audio[silence_end_sample:]

    print(f"         Removed first {silence_end_sample/sr:.2f}s (noise estimation region)")
    print(f"         Duration: {len(before)/sr:.2f}s → {len(audio_trimmed)/sr:.2f}s")

    plot_comparison(before, audio_trimmed, sr, sr,
                    "Remove silence prefix",
                    "6: Trim Silence Region")

    return audio_trimmed


# =============================================================================
# STEP 7: EXPORT TO WAV
# =============================================================================
def step7_export_wav(audio: np.ndarray, sr: int, output_path: str,
                     config: PipelineConfig, report: QualityReport) -> str:
    """
    Export the processed audio as a 16-bit PCM WAV file.

    Bridge2AI reference:
      - Audio resampled to 16 kHz mono
      - Feature extraction via OpenSMILE, Praat/Parselmouth, torchaudio, Whisper
      - All operate on standard WAV input

    Output format: 16-bit PCM WAV, mono, 16 kHz
    """
    print(f"[Step 7] Export to WAV: {output_path}")

    # Scale float32 [-1, 1] to int16 range
    audio_int16 = np.clip(audio * 32767, -32768, 32767).astype(np.int16)

    wavfile.write(output_path, sr, audio_int16)

    report.output_sr = sr
    report.output_duration_sec = len(audio) / sr

    file_size = os.path.getsize(output_path)
    print(f"         Format: PCM WAV, {config.bit_depth}-bit, {sr} Hz, mono")
    print(f"         Duration: {report.output_duration_sec:.2f}s")
    print(f"         File size: {file_size / 1024:.1f} KB")

    return output_path


# =============================================================================
# MAIN PIPELINE
# =============================================================================
def run_pipeline(input_path: str,
                 output_path: str = None,
                 config: PipelineConfig = None,
                 force_continue: bool = False) -> Tuple[Optional[str], QualityReport]:
    """
    Run the complete B2AI-aligned voice preprocessing pipeline.

    Args:
        input_path: Path to input audio file (m4a, caf, wav, mp3, webm, etc.)
        output_path: Path for output WAV file (auto-generated if None)
        config: Pipeline configuration (uses defaults if None)
        force_continue: If True, continue preprocessing even if quality gate fails
                       (output will be flagged in the report)

    Returns:
        (output_wav_path, quality_report)

    Pipeline:
        Quality Gate:
            1. Silence region detection (for noise floor estimation)
            2. SNR check (≥42 ideal, ≥30 acceptable, <30 reject)
            3. Clipping detection (>0.1% clipped samples → reject)
            4. Voice activity detection (≥3s voiced audio required)
            5. AGC detection (warning if automatic gain control detected)

        Preprocessing (if gate passes):
            1. Resample to 16 kHz with Butterworth anti-alias filter
            2. High-pass filter at 80 Hz (mic roll-off compensation)
            3. CMVN spectral normalization (remove mic channel coloring)
            4. LUFS normalization (constant gain, preserves all ratios)
            5. Conditional noise reduction (only if SNR 30-42 dB)
            6. Trim leading silence region
            7. Export as 16-bit PCM WAV
    """
    if config is None:
        config = PipelineConfig()

    if output_path is None:
        base = os.path.splitext(os.path.basename(input_path))[0]
        output_path = f"{base}_b2ai_processed.wav"

    print(f"╔{'═'*58}╗")
    print(f"║  B2AI-Voice Aligned Preprocessing Pipeline               ║")
    print(f"║  Input: {os.path.basename(input_path):<49}║")
    print(f"╚{'═'*58}╝\n")

    # ── Step 0: Load ──
    audio, sr, report = step0_load_audio(input_path, config)
    print()

    # ── Quality Gate ──
    gate_passed, silence_end_sample = run_quality_gate(audio, sr, config, report)

    if not gate_passed and not force_continue:
        print("Pipeline stopped. Set force_continue=True to process anyway.")
        print(report.summary())
        return None, report

    if not gate_passed and force_continue:
        print("⚠ Quality gate FAILED but force_continue=True. Proceeding with warnings.\n")

    # ── Preprocessing ──
    print(f"\n{'='*60}")
    print(f"  PREPROCESSING")
    print(f"{'='*60}\n")

    # Step 1: Resample to 16 kHz
    audio_16k, sr_16k = step1_resample(audio, sr, config)
    silence_end_resampled = int(silence_end_sample * config.target_sr / sr)
    print()

    # Step 2: High-pass filter (microphone roll-off compensation)
    audio_hp = step2_highpass_filter(audio_16k, sr_16k, config, report)
    print()

    # Step 3: CMVN (channel/microphone normalization)
    audio_cmvn = step3_cmvn_compensation(audio_hp, sr_16k, config, report)
    print()

    # Step 4: LUFS normalization (constant gain)
    audio_normalized = step4_normalize_lufs(audio_cmvn, sr_16k, config, report)
    print()

    # Step 5: Conditional noise reduction
    audio_denoised = step5_conditional_noise_reduction(
        audio_normalized, sr_16k, report.gate_snr_verdict,
        silence_end_resampled, config, report)
    print()

    # Step 6: Trim silence
    audio_trimmed = step6_trim_silence(audio_denoised, sr_16k, silence_end_resampled)
    print()

    # Step 7: Export
    output_file = step7_export_wav(audio_trimmed, sr_16k, output_path, config, report)
    print()

    # ── Final Before/After Comparison ──
    print(f"\n{'='*60}")
    print(f"  FINAL COMPARISON: Original Input vs. Processed Output")
    print(f"{'='*60}\n")

    # Resample the original to 16k just for display comparison
    # (so the playback/spectrograms are at the same rate)
    original_for_display = librosa.resample(audio, orig_sr=sr, target_sr=sr_16k)

    fig, axes = plt.subplots(2, 2, figsize=(14, 6))
    fig.suptitle("Full Pipeline: Original Input → Final Output", fontsize=14, fontweight='bold')

    # Original waveform
    t_orig = np.arange(len(original_for_display)) / sr_16k
    axes[0, 0].plot(t_orig, original_for_display, linewidth=0.3, color='#F44336')
    axes[0, 0].set_title(f"Original Input ({sr} Hz → displayed at {sr_16k} Hz)")
    axes[0, 0].set_xlabel("Time (s)")
    axes[0, 0].set_ylabel("Amplitude")
    axes[0, 0].set_ylim(-1.05, 1.05)

    # Processed waveform
    t_proc = np.arange(len(audio_trimmed)) / sr_16k
    axes[0, 1].plot(t_proc, audio_trimmed, linewidth=0.3, color='#4CAF50')
    axes[0, 1].set_title(f"Processed Output ({sr_16k} Hz, silence trimmed)")
    axes[0, 1].set_xlabel("Time (s)")
    axes[0, 1].set_ylabel("Amplitude")
    axes[0, 1].set_ylim(-1.05, 1.05)

    # Original spectrogram
    S_orig = librosa.feature.melspectrogram(y=original_for_display, sr=sr_16k, n_mels=80)
    S_orig_db = librosa.power_to_db(S_orig, ref=np.max)
    librosa.display.specshow(S_orig_db, sr=sr_16k, x_axis='time',
                             y_axis='mel', ax=axes[1, 0], cmap='magma')
    axes[1, 0].set_title("Original — Mel Spectrogram")

    # Processed spectrogram
    S_proc = librosa.feature.melspectrogram(y=audio_trimmed, sr=sr_16k, n_mels=80)
    S_proc_db = librosa.power_to_db(S_proc, ref=np.max)
    librosa.display.specshow(S_proc_db, sr=sr_16k, x_axis='time',
                             y_axis='mel', ax=axes[1, 1], cmap='magma')
    axes[1, 1].set_title("Processed — Mel Spectrogram")

    plt.tight_layout()
    plt.show()

    # Audio playback: original vs final
    print(f"🔊 Original input ({sr} Hz):")
    display(Audio(audio, rate=sr))
    print(f"🔊 Final processed output ({sr_16k} Hz):")
    display(Audio(audio_trimmed, rate=sr_16k))

    # ── Summary ──
    print()
    print(report.summary())

    return output_file, report


# =============================================================================
# CONVENIENCE: GENERATE A SYNTHETIC TEST FILE
# =============================================================================
def generate_test_audio(output_path: str = "test_recording.wav",
                        sr: int = 44100,
                        silence_sec: float = 3.0,
                        vowel_sec: float = 5.0,
                        f0: float = 220.0,
                        noise_level: float = 0.005,
                        add_harmonics: bool = True) -> str:
    """
    Generate a synthetic test recording that mimics a sustained vowel
    with a leading silence period, for testing the pipeline.

    Structure: [silence + noise] [sustained vowel /a/ + noise]
    """
    t_silence = np.arange(int(silence_sec * sr)) / sr
    t_vowel = np.arange(int(vowel_sec * sr)) / sr

    # Background noise (present throughout)
    noise_silence = np.random.randn(len(t_silence)) * noise_level
    noise_vowel = np.random.randn(len(t_vowel)) * noise_level

    # Sustained vowel with harmonics (simulates /a/)
    vowel = 0.3 * np.sin(2 * np.pi * f0 * t_vowel)
    if add_harmonics:
        vowel += 0.15 * np.sin(2 * np.pi * 2 * f0 * t_vowel)  # H2
        vowel += 0.08 * np.sin(2 * np.pi * 3 * f0 * t_vowel)  # H3
        vowel += 0.04 * np.sin(2 * np.pi * 4 * f0 * t_vowel)  # H4
        vowel += 0.02 * np.sin(2 * np.pi * 5 * f0 * t_vowel)  # H5

    # Smooth onset/offset (50ms ramp)
    ramp_samples = int(0.05 * sr)
    ramp = np.linspace(0, 1, ramp_samples)
    vowel[:ramp_samples] *= ramp
    vowel[-ramp_samples:] *= ramp[::-1]

    audio = np.concatenate([noise_silence, vowel + noise_vowel])
    audio = audio.astype(np.float32)

    # Normalize peak
    audio = audio / np.max(np.abs(audio)) * 0.7

    wavfile.write(output_path, sr, (audio * 32767).astype(np.int16))
    print(f"Generated test audio: {output_path}")
    print(f"  Structure: {silence_sec}s silence + {vowel_sec}s vowel at {f0} Hz")
    print(f"  Sample rate: {sr} Hz | Noise level: {noise_level}")
    return output_path


# =============================================================================
# COLAB USAGE EXAMPLE
# =============================================================================
if __name__ == "__main__":
    print("=" * 60)
    print("  B2AI-Voice Pipeline — Demo with Synthetic Audio")
    print("=" * 60)
    print()

    # # Generate a test file
    # test_file = generate_test_audio(
    #     output_path="test_sustained_vowel.wav",
    #     sr=44100,       # Simulate iOS recording at 44.1 kHz
    #     silence_sec=3.0,
    #     vowel_sec=5.0,
    #     f0=220.0,       # A3 — typical male sustained vowel
    #     noise_level=0.003,
    # )
    # print()

    # Run the pipeline
    output, report = run_pipeline(
        # input_path=test_file,
        input_path="test.wav.wav",
        output_path="processed_output.wav",
        force_continue=False,
    )

    # To use with your own recording:
    # ─────────────────────────────────
    # # In Colab, upload a file:
    # from google.colab import files
    # uploaded = files.upload()
    # input_file = list(uploaded.keys())[0]
    #
    # output, report = run_pipeline(
    #     input_path=input_file,
    #     output_path="my_processed_voice.wav",
    # )
    #
    # # Download the result:
    # if output:
    #     files.download(output)

# To use with your own recording:
    # ─────────────────────────────────
    # # In Colab, upload a file:
    # from google.colab import files
    # uploaded = files.upload()
    # input_file = list(uploaded.keys())[0]
    #
    output, report = run_pipeline(
        input_path=input_file,
        output_path="my_processed_voice.wav",
    )
    #
    # # Download the result:
    # if output:
    #     files.download(output)