/**
 * API Service for Voice Health Analysis
 * Interfaces with the Flask backend ML pipeline
 */

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api/v1';

// ─── Backend response shapes (match Flask response.py) ──────────────────────

/** Raw envelope returned by the Flask API */
interface ApiEnvelope {
  status: 'success' | 'error';
  code: number;
  message: string;
  data: Record<string, any> | null;
  errors: {
    type: string;
    suggestion?: string;
    failed_checks?: any[];
    passed_checks?: any[];
    warnings?: any[];
  } | null;
  meta: {
    request_id: string;
    timestamp: string;
    processing_time_ms: number;
  };
}

/** A single condition prediction from the ML pipeline */
export interface ConditionPrediction {
  condition: string;
  condition_name: string;
  probability: number;        // 0.0–1.0
  probability_percent: number; // 0–100
  severity_tier: 'low' | 'moderate' | 'elevated' | 'high';
  features_used: string[];
  feature_values: Record<string, number>;
  reference_thresholds: Record<string, any>;
}

/** Explanation generated by the LLM */
export interface Explanation {
  summary: string;
  details?: string;
  disclaimer?: string;
  model_version?: string;
}

// ─── Frontend-friendly shapes ────────────────────────────────────────────────

export interface AnalysisResult {
  success: boolean;
  data?: {
    quality: Record<string, any>;
    preprocessing?: Record<string, any>;
    features: Record<string, number>;
    predictions: ConditionPrediction[];
    explanation: Explanation;
  };
  error?: {
    type: string;
    message: string;
    suggestion?: string;
  };
  requestId: string;
  processingTimeMs?: number;
}

export interface HealthCheckResult {
  success: boolean;
  data?: {
    version: string;
    model_loaded: boolean;
    model_version: string;
    gpu_available: boolean;
  };
  message: string;
}

// ─── API Functions ───────────────────────────────────────────────────────────

/**
 * Analyze audio file using the ML pipeline.
 * Maps the Flask envelope into a typed AnalysisResult.
 */
export async function analyzeAudio(
  audioBlob: Blob,
  options: {
    deviceId?: string;
    taskType?: 'sustained_vowel' | 'free_speech' | 'reading_passage' | 'cough';
    silenceDuration?: number;
  } = {}
): Promise<AnalysisResult> {
  const formData = new FormData();
  formData.append('audio', audioBlob, 'recording.webm');
  formData.append('device_id', options.deviceId || 'web_app');
  formData.append('task_type', options.taskType || 'reading_passage');
  formData.append('silence_duration_sec', String(options.silenceDuration || 0.5));

  try {
    const response = await fetch(`${API_BASE_URL}/analyze`, {
      method: 'POST',
      body: formData,
    });

    const envelope: ApiEnvelope = await response.json();

    if (envelope.status !== 'success' || !envelope.data) {
      return {
        success: false,
        error: {
          type: envelope.errors?.type || 'unknown_error',
          message: envelope.message || 'Analysis failed',
          suggestion: envelope.errors?.suggestion,
        },
        requestId: envelope.meta?.request_id || 'unknown',
      };
    }

    return {
      success: true,
      data: {
        quality: envelope.data.quality,
        preprocessing: envelope.data.preprocessing,
        features: envelope.data.features,
        predictions: envelope.data.predictions,
        explanation: envelope.data.explanation,
      },
      requestId: envelope.meta.request_id,
      processingTimeMs: envelope.meta.processing_time_ms,
    };
  } catch (error) {
    console.error('API Error:', error);
    return {
      success: false,
      error: {
        type: 'network_error',
        message: error instanceof Error ? error.message : 'Network error occurred',
        suggestion: 'Please check your connection and ensure the backend server is running.',
      },
      requestId: 'local_error',
    };
  }
}

/**
 * Validate audio quality without full analysis.
 */
export async function validateAudio(
  audioBlob: Blob,
  options: {
    deviceId?: string;
    taskType?: string;
    silenceDuration?: number;
  } = {}
): Promise<AnalysisResult> {
  const formData = new FormData();
  formData.append('audio', audioBlob, 'recording.webm');
  formData.append('device_id', options.deviceId || 'web_app');
  formData.append('task_type', options.taskType || 'reading_passage');
  formData.append('silence_duration_sec', String(options.silenceDuration || 0.5));

  try {
    const response = await fetch(`${API_BASE_URL}/validate`, {
      method: 'POST',
      body: formData,
    });

    const envelope: ApiEnvelope = await response.json();

    if (envelope.status !== 'success') {
      return {
        success: false,
        error: {
          type: envelope.errors?.type || 'unknown_error',
          message: envelope.message || 'Validation failed',
          suggestion: envelope.errors?.suggestion,
        },
        requestId: envelope.meta?.request_id || 'unknown',
      };
    }

    return {
      success: true,
      data: {
        quality: envelope.data?.quality || {},
        features: {},
        predictions: [],
        explanation: { summary: '' },
      },
      requestId: envelope.meta.request_id,
    };
  } catch (error) {
    console.error('API Error:', error);
    return {
      success: false,
      error: {
        type: 'network_error',
        message: error instanceof Error ? error.message : 'Network error occurred',
      },
      requestId: 'local_error',
    };
  }
}

/**
 * Check server health.
 */
export async function checkHealth(): Promise<HealthCheckResult> {
  try {
    const response = await fetch(`${API_BASE_URL}/health`);
    const envelope: ApiEnvelope = await response.json();
    return {
      success: envelope.status === 'success',
      data: envelope.data as any,
      message: envelope.message,
    };
  } catch {
    return {
      success: false,
      message: 'Server unavailable',
    };
  }
}

// ─── Helper functions ────────────────────────────────────────────────────────

/**
 * Convert ML feature dict into user-friendly biomarker values.
 *
 * Searches multiple possible key names for each biomarker because
 * the backend feature dict key names depend on the extraction path
 * (senselab B2AI vs Praat fallback).
 */
export function extractBiomarkers(features: Record<string, number>) {
  const get = (keys: string[], fallback: number): number => {
    for (const k of keys) {
      if (features[k] !== undefined && features[k] !== null) return features[k];
    }
    return fallback;
  };

  const pitch = get(
    ['praat.f0.mean_hz', 'pitch_mean', 'f0_mean'],
    210
  );
  const jitter = get(
    ['praat.jitter.local_percent', 'praat.jitter.local.mean', 'jitter_local'],
    1.2
  );
  const shimmer = get(
    ['praat.shimmer.local_percent', 'praat.shimmer.local.mean', 'shimmer_local'],
    3.4
  );
  const hnr = get(
    ['praat.hnr.mean_db', 'praat.harmonicity.mean', 'hnr_mean'],
    18.5
  );
  const spectral = get(
    ['spectral_centroid_mean', 'praat.spectral_centroid.mean'],
    1500
  );

  return {
    pitch: Math.round(pitch),
    jitter: Number(jitter.toFixed(2)),
    shimmer: Number(shimmer.toFixed(2)),
    harmonicRatio: Number(hnr.toFixed(1)),
    spectralCentroid: Math.round(spectral),
  };
}

/**
 * Derive a user-facing message from the ML predictions array and
 * the LLM explanation object.
 */
export function generateMessage(
  predictions: ConditionPrediction[],
  explanation: Explanation
): { message: string; isAnomaly: boolean } {
  if (!predictions?.length || !explanation) {
    return {
      message: 'Analysis complete. Your voice metrics are within normal range.',
      isAnomaly: false,
    };
  }

  // Anomaly if any condition has severity above "low"
  const isAnomaly = predictions.some(
    (p) => p.severity_tier !== 'low'
  );

  let message = explanation.summary || 'Your voice analysis is complete.';

  if (explanation.details) {
    message += ' ' + explanation.details;
  }

  return { message, isAnomaly };
}
